### ISSUE TITLE
Java 8 + Spring 4.1.4 + @Configure + Constretto

### ISSUE THREAD

**Issue by selbekk** [constretto/constretto-core#52]
I experienced an issue while writing some java 8 code in a class having the following setter:

    @Configure
    public void setDatabaseDriverClass(@Configuration(value = "internal.database.jdbc.driverClassName") String internalDatabaseClassName) {
        this.internalDatabaseClassName = internalDatabaseClassName;
    }

Worked beautifully when there's no java 8 code in that particular class, but as soon as you even _mention_ ``.stream()``, you get this error during initialization of Spring:

    Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'reportDao' defined in file [<...>/ReportDao.class]: Initialization of bean failed; nested exception is java.lang.ArrayIndexOutOfBoundsException: 33571681
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:547)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:476)
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:303)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:299)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:194)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.findAutowireCandidates(DefaultListableBeanFactory.java:1127)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1051)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:949)
	at org.springframework.beans.factory.support.ConstructorResolver.resolveAutowiredArgument(ConstructorResolver.java:813)
	at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:741)
	... 46 more
    Caused by: java.lang.ArrayIndexOutOfBoundsException: 33571681
	at com.thoughtworks.paranamer.BytecodeReadingParanamer$ClassReader.readInt(BytecodeReadingParanamer.java:726)
	at com.thoughtworks.paranamer.BytecodeReadingParanamer$ClassReader.accept(BytecodeReadingParanamer.java:563)
	at com.thoughtworks.paranamer.BytecodeReadingParanamer$ClassReader.access$200(BytecodeReadingParanamer.java:337)
	at com.thoughtworks.paranamer.BytecodeReadingParanamer.lookupParameterNames(BytecodeReadingParanamer.java:105)
	at com.thoughtworks.paranamer.BytecodeReadingParanamer.lookupParameterNames(BytecodeReadingParanamer.java:71)
	at org.constretto.internal.DefaultConstrettoConfiguration.injectMethods(DefaultConstrettoConfiguration.java:297)
	at org.constretto.internal.DefaultConstrettoConfiguration.injectConfiguration(DefaultConstrettoConfiguration.java:278)
	at org.constretto.internal.DefaultConstrettoConfiguration.on(DefaultConstrettoConfiguration.java:153)
	at org.constretto.spring.ConfigurationAnnotationConfigurer.injectConfiguration(ConfigurationAnnotationConfigurer.java:81)
	at org.constretto.spring.ConfigurationAnnotationConfigurer.postProcessAfterInstantiation(ConfigurationAnnotationConfigurer.java:57)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1164)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:537)
	... 56 more

This ``ArrayIndexOutOfBoundsException`` is typically something we've seen while writing Java 8 code in classes with dependencies (direct or transient) that do not support Java 8 bytecode yet.

We resolved the issue by autowiring in a ``ConstrettoConfiguration`` in the constructor and setting the property there instead - but this is obviously an error that you might want to look into. 

I even tried excluding your (somewhat dated) dependency on [paranamer](https://github.com/paul-hammant/paranamer) and depend on the newest version directly - without any success.

We're using Spring 4.1.4 and Constretto 2.2.1.

**Comment by zapodot** [comment]
I will look into it, but as for Constretto 2.X we can't give any gurateees when used together with Spring 4.X or Java 8. Paranamer relies heavily on reading your bytecode which may cause problems when the source is compiled with 1.8 as target. I am not sure that that is in fact why you get these errors  as it need a more thorough investigation... A workaround would be to use field based configuration injection instead of a seperate @Configure method as that would not involve using anything but standard Java Reflection to resolve the property names.

As Paranamer is just another way of doing what may be solved in Java 8 by enabling the "-parameters" switch when compiling, we probably should look into supporting that as a strategy when it's enabled and thus remove the need to include Paranamer. 

This would however mean that we would have to create a Java 8 add-on that could be dynamically enabled (which may be a good idea for other reasons as well).

**Comment by selbekk** [comment]
Fair enough. However, I couldn't find any information about either of those two caveats in your Readme. Perhaps it's worth adding?

That being said - we've been using Java 8 for quite some time now in production, and Constretto for even longer, and this was the first problem we encountered with the two combined.

**Comment by zapodot** [comment]
Thanx for reporting back @selbekk 

I will add a note to the readme

**Comment by sherriff** [comment]
Any developments on this issue? 
Using java8, Constretto 2.2.2 and Spring 4.1.6 and I get the same problem. Tried setter and constructor. 
Any workaround I can try?

**Comment by zapodot** [comment]
Sure. It seems to be resolved in the Constretto-3 branch which is not
released yet. You can try it out by updating to 3.0.0-SNAPSHOT (and include
the sonatype Snapshot repo in your maven config). Note: the Constretto-3
branch is in an early stage of development and is as such not "production
ready".

Feedback on the 3.0.0-SNAPSHOT version is most welcome!

Sondre

**Comment by LeonardMeyer** [comment]
@zapodot Any ETA/roadmap available for the 3rd version ?

**Comment by zapodot** [comment]
The list of proposed features/changes is not too long as you can se from [here](//github.com/constretto/constretto-core/milestones/Constretto%203.0). 

Unfortunately, I have been rather busy lately and have not have enough time at hand to work on the Constretto-3 branch. I am however hoping to find some time pretty soon to get it done. I am more than happy to consider pull requests if you or someone else would like to contribute. 

Closing this issue for now as it will surely be fixed in issue #51
